# server:
#   port: 9002
spring:
  main:
    banner-mode: off
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_dev?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    defer-datasource-initialization: false
    show-sql: false
  sql:
    init:
      platform: mysql
      mode: embedded
      schema-locations:
      data-locations:
#To register with eureka at port 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
